name: medibridge
description: A comprehensive healthcare mobile application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  flutter_local_notifications: ^16.3.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  intl: ^0.18.1
  dialogflow_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
  # Removed platform-specific url_launcher packages
  # url_launcher_android: ^6.1.6
  # url_launcher_ios: ^6.1.6
  # url_launcher_web: ^2.0.6
  # url_launcher_windows: ^3.0.0
  # url_launcher_macos: ^6.1.6
  # url_launcher_linux: ^6.1.6 