name: medibridge
description: A comprehensive healthcare mobile application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
  url_launcher: ^6.1.6
  intl: ^0.20.2
  dialogflow_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  # Removed platform-specific url_launcher packages
  # url_launcher_android: ^6.1.6
  # url_launcher_ios: ^6.1.6
  # url_launcher_web: ^2.0.6
  # url_launcher_windows: ^3.0.0
  # url_launcher_macos: ^6.1.6
  # url_launcher_linux: ^6.1.6 